services:
  - type: web
    name: arabic-hall-booking-system
    env: node
    buildCommand: npm ci --no-audit --no-fund && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false